config/routes.rb
Rails.application.routes.draw do

  get "movie/:id/mail" => "movies#mail", :as => 'mail_movie'
  get "movie/:id/spam" => "movies#spam", :as => 'spam_movie'

  get 'rental/index'
  get 'rental/show/:id' => "rental#show", :as => 'rental_show'

  devise_for :users

  resources :movies do
    get 'page/:page', :action => :index, :on => :collection
    resources :comments
  end

  get 'people/index'
  get 'home' => "page#home"
  get 'about_us' => "page#about_us"

  match "contact_us" => "page#contact_us", :via => [:post, :get]

  get 'newsletter'=> "page#newsletter"
  get 'blog' => "page#blog"

  get 'calendar(/:year(/:month))' => "page#calendar", :as => 'calendar'

  get 'articles' => "page#articles"
  get 'login' => "page#login"

  get 'nolboo/teach'
  get 'nolboo/speak'
  get 'nolboo/dig'

  get 'say/hello' # => 'say#hello'
  get "say/goodbye"
  get "say/something"

  root 'page#home'

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy, :mail, :spam]
  before_filter :authenticate, except: [ :index, :show ]

  def mail    # mail_movie_path
    UserMailer.newsletter(@movie, current_user ).deliver
    redirect_to @movie, notice: 'Email sent.'
  end

  def spam    # spam_movie_path
    # Get all of the users
    # Loop through and send an email to each one
    users = User.all #where ( :newsletter => true )
    users.each do | user |
      UserMailer.newsletter(@movie, user).deliver
    end
    redirect_to movies_path, notice: 'Email sent.'
  end

  # GET /movies
  # GET /movies.json
  def index
    # @prev_page = @page - 1 unless @page == 0
    # @next_page = @page + 1 unless (@page*5 > Movie.count)
    # @movies = Movie.limit(5).offset(@page * 5).order(:updated_at => :desc)
    @movies = Movie.page(params['page']).order(:updated_at => :desc)
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @comment = Comment.new
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def authenticate
      authenticate_user! && current_user.try( :admin? )
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:name, :director, :description, :year, :length, :format, :image, :thumbnail)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_comment_form.erb
<%= tinymce_assets %>
<%= tinymce %>
<%= form_for([@movie, @comment]) do |f| %>
    <% if @comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
            <% @comment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :author %><br>
      <%= f.text_field :author %>
    </div>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content, :class => "tinymce" %>
    </div>
    <div class="field">
      <%= f.label :rating %><br>
      <%= f.number_field :rating %>
    </div>
    <%= f.hidden_field :movie_id %>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/movies/_form.html.erb
<%= tinymce %>
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "tinymce" %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.text_field :length %>
  </div>
  <div class="field">
    <%= f.label :format %><br>
    <%= f.text_field :format %>
  </div>
    <div class="field">
      <%= f.label :image %><br>
      <%= f.text_field :image %>
    </div>
    <div class="field">
      <%= f.label :thumbnail %><br>
      <%= f.text_field :thumbnail %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<%= tinymce_assets %>
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movies</h1>

<%= paginate @movies %>
<%#= link_to "Previous", movies_path(:page => @prev_page) %>
<%#= link_to "Next", movies_path(:page => @next_page) %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Director</th>
      <th>Description</th>
      <th>Year</th>
      <th>Length</th>
      <th>Format</th>
      <th>Thumbnail</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.id %></td>
        <td><%= link_to movie.proper_name, movie %></td>
        <td><%= movie.director %></td>
        <td><%= truncate( movie.description.html_safe, :length => 20 ) %></td>
        <td><%= movie.year %></td>
        <td><%= movie.length %></td>
        <td><%= movie.format %></td>
        <td><%= link_to( image_tag(movie.thumbnail), movie ) %></td>
        <td><%= link_to 'Show', movie %></td>
        <% if current_user.try(:admin?) %>
            <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
            <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <td><%= link_to 'Email', spam_movie_path( movie ) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p> Average Rating: <%= stars( @movie.comments.average(:rating).round ) %></p>
<p>
  <strong>Name:</strong>
  <%= @movie.proper_name %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movie.director %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description.html_safe %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Length:</strong>
  <%= @movie.length %>
</p>

<p>
  <strong>Format:</strong>
  <%= @movie.format %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @movie.image %>
</p>

<p>
  <strong>Thumbnail Image:</strong>
  <%= image_tag @movie.thumbnail %>
</p>
<h3>Comments</h3>
<% @movie.comments.descending.each do | comment | %>
    <h3><%= comment.title %></h3>
    <h3>about <%= time_ago_in_words(comment.created_at)  %> ago, <%= comment.author %> said: </h3>
    <p><%= comment.content %></p>
    <p>Rating: <%= stars(comment.rating) %></p>
    <% if is_admin? %>
        <%= link_to "Delete Comment", movie_comment_path(@movie, comment), data: { :confirm => 'Are you sure?' }, :method => :delete %>
    <% end %>
    <hr/>
<% end %>

<%= render :partial => 'comment_form' %>

<%= link_to 'Email this movie', mail_movie_path( @movie ) %>
<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>