config/routes.rb
Rails.application.routes.draw do

  get "movie/:id/mail" => "movies#mail", :as => 'mail_movie'
  get "movie/:id/spam" => "movies#spam", :as => 'spam_movie'

  get 'rental/index'
  get 'rental/show/:id' => "rental#show", :as => 'rental_show'

  devise_for :users

  resources :movies do
    get 'page/:page', :action => :index, :on => :collection
    resources :comments
  end

  get 'people/index'
  get 'home' => "page#home"
  get 'about_us' => "page#about_us"

  match "contact_us" => "page#contact_us", :via => [:post, :get]

  get 'newsletter'=> "page#newsletter"
  get 'blog' => "page#blog"

  get 'calendar(/:year(/:month))' => "page#calendar", :as => 'calendar'

  get 'articles' => "page#articles"
  get 'login' => "page#login"

  get 'nolboo/teach'
  get 'nolboo/speak'
  get 'nolboo/dig'

  get 'say/hello' # => 'say#hello'
  get "say/goodbye"
  get "say/something"

  root 'page#home'

end

app/views/shared/_nav.html.erb
<nav><!-- top nav -->
  <div class="menu">
    <ul>
      <li><%= nav_link_to "Home", "home", home_path, "current_page" %></li>
      <li><%= nav_link_to "About", "about_us", about_us_path, "current_page" %>
        <ul>
          <li><%= nav_link_to "Contacts Us", "contact_us", contact_us_path, "current_page" %></li>
        </ul>
      </li>
      <li><%= nav_link_to "Calendar", "calendar", calendar_path, "current_page" %></li>
      <li><%= nav_link_to "Articles", "articles", articles_path, "current_page" %>
          <ul>
            <li><%= nav_link_to "Newsletter", "newsletter", newsletter_path, "current_page" %></li>
          </ul>
      </li>
      <li><%= nav_link_to "Blog", "bolg", blog_path, "current_page" %></li>
      <% if user_signed_in? %>
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
      <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>

    </ul>
  </div>
</nav><!-- end of top nav -->
<% if user_signed_in? %>
    Welcome, <%= current_user.full_name %><br/>
<% end %>