config/routes.rb
Rails.application.routes.draw do

  get "movie/:id/mail" => "movies#mail", :as => 'mail_movie'
  get "movie/:id/spam" => "movies#spam", :as => 'spam_movie'

  get 'rental/index'
  get 'rental/show/:id' => "rental#show", :as => 'rental_show'

  devise_for :users

  resources :movies do
    get 'page/:page', :action => :index, :on => :collection
    resources :comments
  end

  get 'people/index'
  get 'home' => "page#home"
  get 'about_us' => "page#about_us"

  match "contact_us" => "page#contact_us", :via => [:post, :get]

  get 'newsletter'=> "page#newsletter"
  get 'blog' => "page#blog"

  get 'calendar(/:year(/:month))' => "page#calendar", :as => 'calendar'

  get 'articles' => "page#articles"
  get 'login' => "page#login"

  get 'nolboo/teach'
  get 'nolboo/speak'
  get 'nolboo/dig'

  get 'say/hello' # => 'say#hello'
  get "say/goodbye"
  get "say/something"

  root 'page#home'

end

app/controllers/rental_controller.rb
class RentalController < ApplicationController
  def index
    @movies = Movie.page(params['page']).order(:updated_at => :desc)
  end

  def show
    @movie = Movie.find( params['id'])
  end
end

app/helpers/rental_helper.rb
module RentalHelper
end

app/views/rental/index.html.erb
<% if is_admin? %>
    <h2>ADMIN!</h2>
    <%= link_to "Movies Admin", movies_path %>
<% end %>
<h1>Listing Movies</h1>

<%= paginate @movies %>
<%#= link_to "Previous", movies_path(:page => @prev_page) %>
<%#= link_to "Next", movies_path(:page => @next_page) %>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Director</th>
    <th>Description</th>
    <th>Year</th>
    <th>Length</th>
    <th>Format</th>
    <th>Thumbnail</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.proper_name, rental_show_path( movie.id ) %></td>
        <td><%= movie.director %></td>
        <td><%= truncate( movie.description.html_safe, :length => 20 ) %></td>
        <td><%= movie.year %></td>
        <td><%= movie.length %></td>
        <td><%= movie.format %></td>
        <td><%= link_to( image_tag(movie.thumbnail), rental_show_path( movie.id ) ) %></td>
        <td><%= link_to 'Show', rental_show_path( movie.id ) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/rental/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movie.proper_name %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movie.director %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description.html_safe %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Length:</strong>
  <%= @movie.length %>
</p>

<p>
  <strong>Format:</strong>
  <%= @movie.format %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @movie.image %>
</p>

<p>
  <strong>Thumbnail Image:</strong>
  <%= image_tag @movie.thumbnail %>
</p>

<%= link_to 'Back', rental_index_path %>